using Asaki.Core;
using Asaki.Core.Configuration;
using Asaki.Core.Context;
using UnityEngine;

namespace Game.Test
{
	[AsakiSave]
	public partial class AsakiWeaponConfigExample : IAsakiConfig
	{
		[AsakiSaveMember] public int Id { get; set; }
		[AsakiSaveMember] public string WeaponAssetPath { get; set; }

	}

	/*
	// <auto-generated/>
	// 生成时间: 12/22/2025 19:32:24
	using Asaki.Core.Serialization;
	using UnityEngine;
	using System.Collections.Generic;
	using System;

	namespace Game.Test
	{
	    partial class AsakiWeaponConfigExample : IAsakiSavable
	    {
	        // WARNING: This is a configuration type. Direct serialization is restricted for safety.
	        private bool _allowConfigSerialization = false;

	        /// <summary>
	        /// Internal method to enable config serialization. This should ONLY be called by the config system.
	        /// </summary>
	        internal void AllowConfigSerialization(bool allow = true)
	        {
	            _allowConfigSerialization = allow;
	        }

	        public void Serialize(IAsakiWriter writer)
	        {
	            // SECURITY CHECK: Prevent accidental serialization of config objects
	            if (!_allowConfigSerialization)
	            {
	                throw new InvalidOperationException("Security violation: Attempt to serialize configuration object 'AsakiWeaponConfigExample'. " +
	                    "Configuration objects should NEVER be saved in game saves. " +
	                    "Instead, save only the configuration ID and reload the config when needed.");
	            }

	            writer.BeginObject("AsakiWeaponConfigExample");
	            writer.WriteInt("Id", this.Id);
	            writer.WriteString("WeaponAssetPath", this.WeaponAssetPath);
	            writer.EndObject();
	        }

	        public void Deserialize(IAsakiReader reader)
	        {
	            this.Id = reader.ReadInt("Id");
	            this.WeaponAssetPath = reader.ReadString("WeaponAssetPath");
	        }
	    }
	}

	 */

	public class ConfigExample : MonoBehaviour
	{
		[ContextMenu("Query")]
		public void Query()
		{
			var weapon = AsakiContext.Get<IAsakiConfigService>().Get<AsakiWeaponConfigExample>(0);
			if(weapon != null)
			{
				Debug.Log(weapon.WeaponAssetPath);
			}
			else
			{
				Debug.LogError("Weapon config not found.");
			}
		}
	}
}
