using Asaki.Core;
using Asaki.Core.Attributes;
using Asaki.Core.MVVM;
using System;
using UnityEngine;

namespace Game.Test
{
	[AsakiBind]
	public partial class AsakiMVVMExampleModel
	{
		public AsakiProperty<int> Health;
		public int Level;
	}

	/*
	// <auto-generated/>
	// 生成时间: 12/22/2025 18:10:13
	using System;
	using UnityEngine;
	using Asaki.Core.MVVM;

	namespace Game.Test
	{
	    public partial class AsakiMVVMExampleModel
	    {
	        public enum PropertyId
	        {
	            Health,
	        }

	        public object GetProperty(PropertyId id)
	        {
	            switch (id)
	            {
	                case PropertyId.Health: return this.Health;
	            }
	            return null;
	        }

	        /// <summary>
	        /// 绑定到 Action 委托 (便捷模式)
	        /// </summary>
	        public void BindHealth(Action<int> action)
	        {
	            if (this.Health != null) this.Health.Subscribe(action);
	        }

	        /// <summary>
	        /// 绑定到 Observer 结构体 (高性能 ZeroGC 模式)
	        /// </summary>
	        public void BindHealth(IAsakiObserver<int> observer)
	        {
	            if (this.Health != null) this.Health.Bind(observer);
	        }

	    }
	}

	 */

	public class MVVMExample : MonoBehaviour
	{
		private void Start()
		{
			AsakiMVVMExampleModel model = new AsakiMVVMExampleModel();
			model.BindHealth(OnHealthUpdate);
		}

		public void OnHealthUpdate(int headlth)
		{
			Debug.Log(headlth.ToString());
		}
	}
}
